### PR TITLE
style changes + fellowship example + adjustments per NOT-OD-21-073

### PR DESCRIPTION
**Pull request by corybrunson**
Hi @pmagwene,

I've maintained this fork for a while for my own purposes but thought i should check with you about merging them in due to the recent NIH biosketch changes. Though the fork includes other changes, some of which i would be glad to revert for the sake of a PR:

1. a6c32d4278f9307119339fe6ee6a61dbc9a2d706 I changed some section header styles and spacing parameters to (i think) more accurately follow the guidelines.
2. 54e23ab174d844315a1c71799782f112d805790e I began tracking a fellowship / postdoc example and rendered PDFs of both examples.
3. 87537a7f0960aa4f01d67792a3c4743b492d54c5 I updated the LICENSE and named myself the maintainer for the version on this fork. **The wording should be changed if you decide to accept this PR.**
4. d19cce160f45f785ef930aae3acbbeb1658c3ee4 Normal underlining is specified when the ulem package is required. This was merged from @abbynoyce's [fork](https://github.com/abbynoyce/latex-nihbiosketch/).
5. 447b08dce6be7a5ff24aaeba7c107dff1f82e01f I discontinued the use of `\headersize` in the style class, since it uses up space and is not required (the NIH Word templates sometimes use slightly larger font and sometimes don't).
6. 4f0a177c515e4d8c9d5b958d762f04a78b638fe9 I added ".DS_Store" and "ignore" (a custom folder where i keep NIH templates) to ".gitignore".
7. e50c0fd5f6348bedf7c8d01784ac89592e1d42bf I added "Scientific Appointments", removed "Research Support", and reordered the Positions, Scientific Appointments, and Honors to adhere to [NOT-OD-21-073](https://grants.nih.gov/grants/guide/notice-files/NOT-OD-21-073.html).
8. ddf5f0cff01118edef38a7662d8730431c9e95b3 I updated the README to mention these updates and to mention the fellowship example.

Thank you for building the original class! It has come very much in handy.

### CODE REVIEW

**Comment by pmagwene** [comment]
@corybrunson Thanks for this. Having had to recently update my own biosketch to conform to the new format, this was on my mind. When I get a free moment I'll merge your changes with ones I had similarly been working on and then push to CRAN .

**Comment by corybrunson** [comment]
Hi @pmagwene, just checking in on this front! It's not urgent for me, but NIH has begun requiring the new guidelines.

**Review by pmagwene — APPROVED** [review]

**Review by pmagwene — APPROVED** [review]
Generally looks good.

Please revise

**Comment by pmagwene** [comment]
Please revert maintainer changes, while  adding a contributors list with details of your contributions (update to NOT-OD-21-110 and addition of fellowship biosketch).

**Comment by corybrunson** [comment]
@pmagwene all is ready! I confirmed with @abbynoyce to be added as a contributor.

**Pull request merged**
